modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="underwatertreasures"
version="1.0.2"
displayName="Underwater Treasures"
credits="Created using mod maker MCreator - https://mcreator.net/about traditional code editing and vibe-coding."
authors="Antarktidov"
description = "Adds underwater treasures to game."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.underwatertreasures]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.underwatertreasures]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration